backend:
  name: github
  repo: John-Jonathans/Light-house-communion-church-jos
  branch: main
  # LOOK HERE: The slash (/) at the end is the Key to fixing the Google bug:
  base_url: https://light-house-communion-church-jos.vercel.app/
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "images"

collections:
  - name: "books"
    label: "Books"
    folder: "books"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Cover Image", name: "cover", widget: "image"}
      - {label: "Link to Buy", name: "link", widget: "string", required: false}
