backend:
  name: github
  repo: John-Jonathans/Light-house-communion-church-jos
  branch: main
  base_url: https://light-house-communion-church-jos.vercel.app
  auth_endpoint: api/callback

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Main Title", name: "title", widget: "string"}
          - {label: "Welcome Text", name: "intro", widget: "text"}

